### ISSUE TITLE
Баг из-за отсутствия статьи

### ISSUE THREAD

**Issue by xdevm** [4gophers/4gophers.ru#1]
Привет!

Заметил что по адресу http://4gophers.ru/articles/page/12/ какие-то проблемы с вёрсткой. Полез в код и вот что увидел:
![2017-04-30_18 22 01](https://cloud.githubusercontent.com/assets/4389555/25565587/5893711e-2dd2-11e7-9bc8-656c60f4cff3.png)
Статьи в [папке](https://github.com/4gophers/4gophers.ru/tree/master/content/articles) не оказалось.

**Comment by horechek** [comment]
Сейчас должно редиректить на корень

**Comment by xdevm** [comment]
@horechek во, норм
![2017-05-02_13 33 24](https://cloud.githubusercontent.com/assets/4389555/25614755/fa60b3fc-2f3b-11e7-8ed0-76ffff8b1c48.png)
